"""
agents/writer.py - Writes full chapter content in the specified tone
"""
from core.llm import call_llm
from core.config import TONES
from core.memory import BookMemory


SYSTEM_PROMPT = """You are a professional book author. Write full chapter content.

Structure every chapter as:
1. Opening hook (2-3 sentences)
2. Section 1 with clear subheading
3. Section 2 with clear subheading  
4. Section 3 with clear subheading
5. Chapter summary (3-4 sentences)
6. One actionable takeaway or reflection question

Use markdown for subheadings (## for chapter title, ### for sections).
Write naturally and engagingly. Do NOT use bullet lists for the main content — write in prose.
Aim for the target word count. Be specific, not generic.
"""


def run(
    chapter_plan: dict,
    research: dict,
    book_plan: dict,
    tone: str,
    memory: BookMemory,
    target_words: int = 2000,
    tracer=None
) -> str:
    """Write a full chapter. Returns markdown text."""
    ch_num = chapter_plan["num"]
    tone_info = TONES.get(tone, TONES["conversational"])
    prior_summaries = memory.get_prior_summaries(ch_num)
    characters = memory.characters_summary()

    facts_text = "\n".join(research.get("facts", []))
    callbacks_text = "\n".join(research.get("callbacks", []))

    user_prompt = f"""
Book title: {book_plan.get('title', 'Untitled')}
Chapter {ch_num}: {chapter_plan['title']}
Chapter summary: {chapter_plan.get('summary', '')}
Key points: {', '.join(chapter_plan.get('key_points', []))}

TONE: {tone_info['name']}
Tone guidance: {tone_info['description']}
Example opening style: {tone_info['example_opener']}
Avoid: {tone_info['avoid']}

Facts to weave in:
{facts_text}

Callbacks from earlier chapters (reference these naturally):
{callbacks_text if callbacks_text else 'None applicable yet'}

Prior chapter context:
{prior_summaries if prior_summaries else 'This is the first chapter.'}

Characters in this book (for fiction consistency):
{characters if characters else 'N/A'}

Target: ~{target_words} words. Write the complete chapter now.
"""

    text = call_llm(
        system=SYSTEM_PROMPT,
        user=user_prompt,
        tracer=tracer,
        agent_name=f"Writer-Ch{ch_num}",
        max_tokens=3000,
        notes=f"tone={tone}"
    )

    # Store chapter summary in memory
    # Take first non-empty paragraph (skip the title line) as the summary
    paragraphs = [p for p in text.split("\n\n") if p.strip()]
    first_para = paragraphs[1] if len(paragraphs) > 1 else (paragraphs[0] if paragraphs else text)
    memory.set_chapter_summary(ch_num, first_para[:200].strip())

    return text


def write_front_matter(section: str, book_plan: dict, tone: str, tracer=None) -> str:
    """Write front matter sections."""
    tone_info = TONES.get(tone, TONES["conversational"])
    system = "You are a professional book author writing front matter. Be concise and appropriate."
    
    prompts = {
        "copyright": f"Write a standard copyright page for '{book_plan.get('title')}' by {book_plan.get('author_name', 'The Author')}. Include year 2025, rights reserved, brief disclaimer.",
        "dedication": f"Write a warm, brief dedication page for '{book_plan.get('title')}'. 2-3 lines. Tone: {tone_info['name']}.",
        "foreword": f"Write a 200-word foreword for '{book_plan.get('title')}' — {book_plan.get('subtitle', '')}. Target audience: {book_plan.get('target_audience', 'general readers')}. Tone: {tone_info['name']}.",
        "preface": f"Write a 200-word author's preface for '{book_plan.get('title')}'. Explain why this book exists and what readers will gain. Tone: {tone_info['name']}.",
        "toc": "placeholder"  # Generated by assembler
    }

    if section == "toc":
        return "TOC_PLACEHOLDER"

    prompt = prompts.get(section, f"Write the {section} section for '{book_plan.get('title')}'.")
    return call_llm(system=system, user=prompt, tracer=tracer, agent_name=f"Writer-{section}", max_tokens=600)


def write_back_matter(section: str, book_plan: dict, memory: BookMemory, tone: str, tracer=None) -> str:
    """Write back matter sections."""
    tone_info = TONES.get(tone, TONES["conversational"])
    system = "You are a professional book author writing back matter. Be concise and well-crafted."

    if section == "glossary":
        terms = memory.get_glossary()
        if terms:
            lines = "\n".join(f"**{t['term']}**: {t['definition']}" for t in terms)
            return f"## Glossary\n\n{lines}"
        return "## Glossary\n\nKey terms and definitions will be added here."

    if section == "references":
        facts = memory.all_facts_text()
        return call_llm(
            system=system,
            user=f"Write a references/further reading section for '{book_plan.get('title')}'. Format as a numbered list of plausible book and article titles with authors. 8-10 items. Relevant to: {facts[:300]}",
            tracer=tracer, agent_name="Writer-references", max_tokens=500
        )

    prompts = {
        "afterword": f"Write a 200-word afterword for '{book_plan.get('title')}'. Reflect on the journey and leave readers inspired. Tone: {tone_info['name']}.",
        "about_author": f"Write a 100-word 'About the Author' bio for {book_plan.get('author_name', 'the author')} of '{book_plan.get('title')}'. Make it credible and warm.",
        "back_cover": f"Write compelling back-cover copy for '{book_plan.get('title')}' — {book_plan.get('subtitle', '')}. Tagline: {book_plan.get('tagline', '')}. 100-150 words. Sell the book. Tone: {tone_info['name']}."
    }

    prompt = prompts.get(section, f"Write the {section} section.")
    return call_llm(system=system, user=prompt, tracer=tracer, agent_name=f"Writer-{section}", max_tokens=500)
