"""
agents/writer.py - Writes full chapter content and all front/back matter in the specified tone.

Tone cascades through EVERY surface — chapters, preface, afterword, glossary definitions,
about-the-author, back-cover copy. Each section has tone-specific prompt guidance.
"""
from core.llm import call_llm
from core.config import TONES
from core.memory import BookMemory


SYSTEM_PROMPT = """You are a professional book author. Write full chapter content.

Structure every chapter as:
1. Opening hook (2-3 sentences)
2. Section 1 with clear subheading
3. Section 2 with clear subheading
4. Section 3 with clear subheading
5. Chapter summary (3-4 sentences)
6. One actionable takeaway or reflection question

Use markdown for subheadings (## for chapter title, ### for sections).
Write naturally and engagingly. Do NOT use bullet lists for the main content — write in prose.
Aim for the target word count. Be specific, not generic.
"""


def run(
    chapter_plan: dict,
    research: dict,
    book_plan: dict,
    tone: str,
    memory: BookMemory,
    target_words: int = 2000,
    tracer=None
) -> str:
    """Write a full chapter. Returns markdown text."""
    ch_num = chapter_plan["num"]
    tone_info = TONES.get(tone, TONES["conversational"])
    prior_summaries = memory.get_prior_summaries(ch_num, tracer=tracer, agent=f"Writer-Ch{ch_num}")
    characters = memory.characters_summary()

    facts_text = "\n".join(research.get("facts", []))
    callbacks_text = "\n".join(research.get("callbacks", []))

    user_prompt = f"""
Book title: {book_plan.get('title', 'Untitled')}
Chapter {ch_num}: {chapter_plan['title']}
Chapter summary: {chapter_plan.get('summary', '')}
Key points: {', '.join(chapter_plan.get('key_points', []))}

TONE: {tone_info['name']}
Tone guidance: {tone_info['description']}
Example opening style: {tone_info['example_opener']}
Avoid: {tone_info['avoid']}
Second person ("you"): {'YES — address the reader directly' if tone in ('conversational', 'motivational') else 'sparingly or not at all'}

Facts to weave in:
{facts_text}

Callbacks from earlier chapters (reference these naturally):
{callbacks_text if callbacks_text else 'None applicable yet'}

Prior chapter context:
{prior_summaries if prior_summaries else 'This is the first chapter.'}

Characters in this book (for fiction consistency):
{characters if characters else 'N/A'}

Target: ~{target_words} words. Write the complete chapter now.
"""

    text = call_llm(
        system=SYSTEM_PROMPT,
        user=user_prompt,
        tracer=tracer,
        agent_name=f"Writer-Ch{ch_num}",
        max_tokens=3500,
        notes=f"tone={tone}"
    )

    # Store chapter summary in memory with tracer
    paragraphs = [p for p in text.split("\n\n") if p.strip()]
    first_para = paragraphs[1] if len(paragraphs) > 1 else (paragraphs[0] if paragraphs else text)
    memory.set_chapter_summary(ch_num, first_para[:200].strip(), tracer=tracer, agent=f"Writer-Ch{ch_num}")

    return text


def write_front_matter(section: str, book_plan: dict, tone: str, tracer=None) -> str:
    """Write front matter sections with tone cascading through every surface."""
    tone_info = TONES.get(tone, TONES["conversational"])
    tone_name = tone_info["name"]
    tone_desc = tone_info["description"]
    tone_avoid = tone_info["avoid"]
    title = book_plan.get("title", "Untitled")
    author = book_plan.get("author_name", "The Author")
    subtitle = book_plan.get("subtitle", "")
    audience = book_plan.get("target_audience", "general readers")

    system = f"""You are a professional book author writing front matter for a {tone_name}-toned book.
Tone: {tone_desc}
Avoid: {tone_avoid}
Output ONLY the section text. No meta-commentary."""

    if section == "toc":
        return "TOC_PLACEHOLDER"  # Generated by assembler

    prompts = {
        "half_title": f"Write a half-title page for '{title}'. Just the title and optionally a very short tagline. {tone_name} feel.",

        "copyright": (
            f"Write a complete copyright page for '{title}' by {author}.\n"
            "Include:\n"
            "- Copyright © 2025 [Author Name]\n"
            "- ISBN placeholder: 978-0-000000-00-0\n"
            "- Edition: First Edition, 2025\n"
            "- Rights reserved statement\n"
            "- CIP (Cataloguing in Publication) data block placeholder\n"
            "- Brief disclaimer\n"
            "Format as a standard book copyright page."
        ),

        "dedication": (
            f"Write a warm, brief dedication page for '{title}'. 2-4 lines only.\n"
            f"Tone: {tone_name}. "
            + ("Make it personal and heartfelt." if tone in ("conversational", "storyteller", "motivational")
               else "Keep it dignified and sincere." if tone == "academic"
               else "A touch of wit is welcome.")
        ),

        "epigraph": (
            f"Write an epigraph (a short inspiring or thought-provoking quote) for '{title}'.\n"
            f"Choose or craft one quote (with attribution) that sets the thematic tone. "
            f"Should feel: {tone_desc}"
        ),

        "foreword": (
            f"Write a 200-250 word foreword for '{title}' — {subtitle}.\n"
            f"Target audience: {audience}.\n"
            f"Tone: {tone_name} — {tone_desc}\n"
            f"The foreword should: explain why this book matters, who wrote it (a respected peer), "
            f"and what the reader will gain. Match the book's {tone_name} voice throughout."
        ),

        "preface": (
            f"Write a 200-250 word author's preface for '{title}'.\n"
            f"Tone: {tone_name} — {tone_desc}\n"
            f"Explain: why the author wrote this book, what personal experience drove it, "
            f"and what readers should expect. The preface voice MUST match the {tone_name} tone exactly.\n"
            + ("Use 'you' language and personal anecdotes." if tone in ("conversational", "motivational")
               else "Use first person but formal register." if tone == "academic"
               else "Set a scene or tell a brief story." if tone == "storyteller"
               else "Be clever and self-aware.")
        ),

        "acknowledgments": (
            f"Write a 150-200 word acknowledgments page for '{title}' by {author}.\n"
            f"Tone: {tone_name}. Thank: editors, researchers, early readers, family.\n"
            + ("Keep it warm and personal — 'you' language is fine." if tone == "conversational"
               else "Maintain formality and brevity." if tone == "academic"
               else "Weave in a small story or metaphor." if tone == "storyteller"
               else "Make it energetic and grateful." if tone == "motivational"
               else "A dry witty observation about the writing process is welcome.")
        ),

        "introduction": (
            f"Write a 300-400 word introduction for '{title}'.\n"
            f"Tone: {tone_name} — {tone_desc}\n"
            f"The introduction should: hook the reader, explain what this book covers and why it matters, "
            f"briefly describe how the chapters are organised, and tell the reader what they'll be able to do "
            f"after reading. This is the FIRST numbered page — make it memorable.\n"
            f"Address the reader as 'you' where appropriate for {tone_name} tone."
        ),
    }

    prompt = prompts.get(section, f"Write the {section} section for '{title}'. Tone: {tone_name}.")
    max_tok = 700 if section in ("foreword", "preface", "introduction", "acknowledgments") else 400
    return call_llm(system=system, user=prompt, tracer=tracer, agent_name=f"Writer-{section}", max_tokens=max_tok)


def write_back_matter(section: str, book_plan: dict, memory: BookMemory, tone: str, tracer=None) -> str:
    """Write back matter sections — tone cascades through every surface."""
    tone_info = TONES.get(tone, TONES["conversational"])
    tone_name = tone_info["name"]
    tone_desc = tone_info["description"]
    tone_avoid = tone_info["avoid"]
    title = book_plan.get("title", "Untitled")
    author = book_plan.get("author_name", "The Author")

    system = f"""You are a professional book author writing back matter for a {tone_name}-toned book.
Tone: {tone_desc}
Avoid: {tone_avoid}
Output ONLY the section text. No meta-commentary."""

    if section == "glossary":
        terms = memory.get_glossary()
        if terms:
            # Apply tone to glossary definitions
            tone_gloss_note = {
                "conversational": "Write each definition in plain, friendly language — like explaining to a friend.",
                "academic": "Write each definition in precise, formal language with technical accuracy.",
                "storyteller": "Write each definition as if it's part of a story — vivid and contextual.",
                "motivational": "Write each definition with an empowering spin — connect to reader action.",
                "witty": "Write each definition with a clever, dry twist — informative but memorable.",
            }.get(tone, "")
            gloss_system = f"You are writing glossary definitions for a {tone_name} book. {tone_gloss_note} Output only the definitions in the format: **term**: definition"
            terms_list = "\n".join(f"- {t['term']}: {t['definition']}" for t in terms)
            toned_defs = call_llm(
                system=gloss_system,
                user=f"Rewrite these glossary definitions in {tone_name} tone:\n{terms_list}",
                tracer=tracer, agent_name="Writer-glossary", max_tokens=800
            )
            return f"## Glossary\n\n{toned_defs}"
        return "## Glossary\n\nKey terms and definitions will be added here."

    if section == "references":
        facts = memory.all_facts_text()
        return call_llm(
            system=system,
            user=(
                f"Write a references/further reading section for '{title}'. "
                f"Format as a numbered list of real-sounding book and article titles with authors. 8-10 items. "
                f"Relevant to: {facts[:300]}\n"
                f"Back-cover tone: {tone_name}."
            ),
            tracer=tracer, agent_name="Writer-references", max_tokens=600
        )

    if section == "appendix":
        return call_llm(
            system=system,
            user=(
                f"Write an appendix for '{title}'. Include 1-2 practical reference tables or lists "
                f"relevant to the book's content. Tone: {tone_name}. 200-300 words."
            ),
            tracer=tracer, agent_name="Writer-appendix", max_tokens=500
        )

    you_note = 'Speak directly to them — "you" language.' if tone in ("conversational", "motivational") else ""
    prompts = {
        "afterword": (
            f"Write a 200-250 word afterword for '{title}'.\n"
            f"Tone: {tone_name} — {tone_desc}\n"
            f"Reflect on the journey the reader has taken. Leave them inspired, challenged, or changed. "
            f"{you_note}"
        ),

        "about_author": (
            f"Write a 120-150 word 'About the Author' bio for {author}, author of '{title}'.\n"
            f"Tone: {tone_name}.\n"
            + ("Make it warm, personal, and approachable." if tone == "conversational"
               else "Keep it formal and credential-focused." if tone == "academic"
               else "Tell a small story about the author's background." if tone == "storyteller"
               else "Make it energetic and inspiring." if tone == "motivational"
               else "A dry self-aware note or unexpected detail is welcome.")
        ),

        "back_cover": (
            f"Write compelling back-cover sales copy for '{title}' — {book_plan.get('subtitle', '')}.\n"
            f"Tagline: {book_plan.get('tagline', '')}\n"
            f"Tone: {tone_name} — {tone_desc}\n"
            f"100-150 words. Sell the book. End with the tagline. "
            + ('Address reader as "you".' if tone in ("conversational", "motivational", "witty") else "")
        ),
    }

    prompt = prompts.get(section, f"Write the {section} section for '{title}'. Tone: {tone_name}.")
    return call_llm(system=system, user=prompt, tracer=tracer, agent_name=f"Writer-{section}", max_tokens=600)
